spring:
  application:
    name: homecare
  datasource:
    url: jdbc:mysql://localhost:3306/homecare
    username: homecare
    password: homecare
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: org.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none